export const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
export const PUB_SUB = 'PUB_SUB';
export const NEW_PENDING_ORDER = 'NEW_PENDING_ORDER';
export const NEW_COOKED_ORDER = 'NEW_COOKED_ORDER';
export const NEW_ORDER_UPDATE = 'NEW_ORDER_UPDATE';

//Owner(12): eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTYzMjY2NjMyOX0.yyahUAEizH0eV3N0PP4m5QBzRj2v28WxXOwwZGZEEx8
//Customer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTYzMjYyNzMzMX0.-TuwI6X-03mpazqBHJLoDajLXywZ0NghparuP8HLcGg
//Delivery: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYzMjczMTQ2OX0.1JtV95E-5MV9mDVRJuoh_HLx1ghoIkCDJOsJ4TL2dDg
